name: hello-world
run-name: ${{ github.actor }} is learning
on: 
  pull_request:
    types:
      - opened
      - reopened
jobs:
  sample-job:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: List branches
        run: |
          USERNAME=${{ github.actor }}
          REPO=${{ github.event.repository.name }}
          TOKEN=${{ secrets.NCSU_GITHUB_TOKEN }}
          curl -H "Authorization: Bearer $TOKEN" \
            "https://github.ncsu.edu/api/v3/repos/$USERNAME/$REPO/branches"